---
title: "About Me"
author: Kubilay Usta
format:
  html:
    code-tools: true
    code-fold: true
---

-   Since I was a child, I've always loved math. It's made me good with numbers and helped me think analytically and solve problems. Throughout my university education, I have furthered my skills in various areas such as operations research, optimization and modeling, data analysis, and coding. Additionally, through academic and social responsibilities. I've developed strong teamwork, leadership, and problem-solving skills. As a talented and eager-to-learn engineering prospect, I am seeking an internship opportunity where I can continue to enhance my abilities.

# Education

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2020 - ongoing.

# Internships

-   TUSAŞ

-   HAVELSAN

# Projects

None

# Competencies

```{r, fig.width=10, fig.height=5}
#| code-fold: true
library(ggplot2)

# Örnek veri
data <- data.frame(
  Skill = c("Python", "R", "Excel", "SQL", "VBA", "AutoCad", "Matlab", "Minitab"),
  Point = c("Intermediate", "Basic", "Advanced", "Basic", "Basic", "Intermediate", "Beginner", "Beginner")
)

# 'Point' sütununu faktör olarak tanımlama ve sıralama
data$Point <- factor(data$Point, levels = c("Beginner", "Basic", "Intermediate", "Advanced", "Expert"))

# 'Skill' sütununu 'Point' sıralamasına göre sıralama
data$Skill <- factor(data$Skill, levels = data$Skill[order(data$Point)])

# ggplot ile grafik oluşturma
ggplot(data, aes(x = Skill, y = Point, fill = Point)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("Beginner" = "lightgrey", 
                                "Basic" = "grey", 
                                "Intermediate" = "blue", 
                                "Advanced" = "orange", 
                                "Expert" = "red")) +
  scale_y_discrete(limits = c("Beginner", "Basic", "Intermediate", "Advanced", "Expert")) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 12, face = "bold"), 
    axis.text.x = element_text(size = 12, face = "bold"),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    legend.position = "none"
  ) +
  labs(title = NULL, x = NULL, y = NULL)

```

# Hobbies

Computer Games

Listen to Music

Hiking

Discussion

Intelligence Games

Fitness

# CV

You can see my CV from this link:

[Kubilay Usta CV](https://www.pdffiller.com/jsfiller-desk17/?mode=ref&lang=en&ref=https%3A%2F%2Fwww.pdffiller.com%2Fen%2Flink_to_fill%2Fmanage.htm%3Fids%5B%5D%3D1385412390%26psk%3D83f8df51-6f99-48a7-95fd-86a37d2d91e4&launch=constructor&projectId=1385412390&loader=tips&MEDIUM_PDFJS=true&PAGE_REARRANGE_V2_MVP=true&richTextFormatting=true&isPageRearrangeV2MVP=true&jsf-page-rearrange-v2=true&jsf-new-header=false&jsf-redesign-full=false&routeId=bff02ac10b128b899f5f1a85d96f7b0a#02fd75a4622f445da2b5cade13bb0fbc "Kubilay Usta CV")

[Python for DataScience.](pythonfordatascience.pdf){.download-button}

[What is Data Science.](whatisdatascience.pdf){.download-button}

[EuroPower Layout Design.](EuroPower.pdf){.download-button}
